### PR TITLE
feat: Lock for specific (python, platform, impl) targets

### PR DESCRIPTION
**Pull request by frostming**
Signed-off-by: Frost Ming <me@frostming.com>

## Pull Request Checklist

- [ ] A news fragment is added in `news/` describing what is new.
- [ ] Test cases added for changed code.

### CODE REVIEW

**Comment by frostming** [comment]
Hi plugin authors:

In this PR, which I would merge shortly, I've made some changes to the public(I wish I have made some of them private though) APIs. While I am trying hard to make the change compatible, I am not sure if it would break downstream projects.

If you have time, could you use the changes in this PR to verify your plugin functionality, ensure there are no disruptions, and that you can see deprecation warnings?

/cc some of the plugin authors： @macro128 @carstencodes @noirbizarre @sigma67

**Comment by sigma67** [comment]
@frostming I am unable today but I will have a look on Sunday

**Comment by macro128** [comment]
Hi! Sure, I'll test my plugin asap and make the changes needed to work with the new lock mechanism

**Comment by carstencodes** [comment]
I am busy this weekend with some weiqi, but I'll check ASAP. 

My current feeling is, that

- pdm-audit plugin won't break: It uses a post install hook (seems unaffected) and calls pdm export under the hood
- pdm-sbom plugin won't break: It parses the lock file directly and the version does not seem to change
- pdm-bump plugin won't break: It is not interested in the dependency tree.

**Comment by frostming** [comment]
@carstencodes Thanks for the feedback. I've listed some breaking changes in the news and other removal, they are basically related to dependencies manipulation and resolution results.

I am asking to see if there is any I missed and whether we can make a compatibility layer for them.

**Pull request merged**
