### PR TITLE
porting to python3.12

### LINKED ISSUE #2300: Supporting python 3.12

### PR DESCRIPTION
**Pull request by laixintao**
## Pull Request Checklist

- [x] A news fragment is added in `news/` describing what is new.
- [x] Test cases added for changed code.

## Describe what you have changed in this PR.

Support Python 3.12

close #2300

### CODE REVIEW

**Comment by frostming** [comment]
Wait what, where does the `pyyaml` dependency come from?

**Comment by laixintao** [comment]
> Wait what, where does the `pyyaml` dependency come from?

```
copier 8.0.0 [ required: >=8.0.0 ]
├── colorama 0.4.6 [ required: >=0.4.3 ]
├── decorator 5.1.1 [ required: >=5.1.1 ]
├── dunamai 1.17.0 [ required: >=1.7.0 ]
│   └── packaging 23.1 [ required: >=20.9 ]
├── funcy 2.0 [ required: >=1.17 ]
├── jinja2 3.1.2 [ required: >=3.1.1 ]
│   └── markupsafe 2.1.3 [ required: >=2.0 ]
├── jinja2-ansible-filters 1.3.2 [ required: >=1.3.1 ]
│   ├── jinja2 3.1.2 [ required: Any ]
│   │   └── markupsafe 2.1.3 [ required: >=2.0 ]
│   └── pyyaml 6.0.1 [ required: Any ]
├── packaging 23.1 [ required: >=23.0 ]
├── pathspec 0.11.1 [ required: >=0.9.0 ]
├── plumbum 1.8.2 [ required: >=1.6.9 ]
├── pydantic 1.10.9 [ required: >=1.10.2 ]
│   └── typing-extensions 4.7.1 [ required: >=4.2.0 ]
├── pygments 2.15.1 [ required: >=2.7.1 ]
├── pyyaml 6.0.1 [ required: >=5.3.1 ]
├── pyyaml-include 1.3 [ required: >=1.2 ]
│   └── pyyaml 6.0.1 [ required: <7.0,>=5.1 ]
└── questionary 1.10.0 [ required: >=1.8.1 ]
    └── prompt-toolkit 3.0.38 [ required: <4.0,>=2.0 ]
        └── wcwidth 0.2.6 [ required: Any ]
keyring 24.1.1 [ required: Any ]
└── jaraco-classes 3.2.3 [ required: Any ]
    └── more-itertools 9.1.0 [ required: Any ]
markdown-exec 1.6.0 [ required: >=0.7.0 ]
└── pymdown-extensions 10.0.1 [ required: >=9 ]
    ├── markdown 3.3.7 [ required: >=3.2 ]
    └── pyyaml 6.0.1 [ required: Any ]
mike 1.1.2 [ required: >=1.1.2 ]
├── jinja2 3.1.2 [ required: Any ]
│   └── markupsafe 2.1.3 [ required: >=2.0 ]
├── mkdocs 1.5.2 [ required: >=1.0 ]
│   ├── click 8.1.3 [ required: >=7.0 ]
│   ├── ghp-import 2.1.0 [ required: >=1.0 ]
│   │   └── python-dateutil 2.8.2 [ required: >=2.8.1 ]
│   │       └── six 1.16.0 [ required: >=1.5 ]
│   ├── jinja2 3.1.2 [ required: >=2.11.1 ]
│   │   └── markupsafe 2.1.3 [ required: >=2.0 ]
│   ├── markdown 3.3.7 [ required: >=3.2.1 ]
│   ├── markupsafe 2.1.3 [ required: >=2.0.1 ]
│   ├── mergedeep 1.3.4 [ required: >=1.3.4 ]
│   ├── packaging 23.1 [ required: >=20.5 ]
│   ├── pathspec 0.11.1 [ required: >=0.11.1 ]
│   ├── platformdirs 3.10.0 [ required: >=2.2.0 ]
│   ├── pyyaml 6.0.1 [ required: >=5.1 ]
│   ├── pyyaml-env-tag 0.1 [ required: >=0.1 ]
│   │   └── pyyaml 6.0.1 [ required: Any ]
│   └── watchdog 3.0.0 [ required: >=2.0 ]
├── pyyaml 6.0.1 [ required: >=5.1 ]
└── verspec 0.1.0 [ required: Any ]
mkdocs-material 9.1.21 [ required: >=7.3 ]
├── colorama 0.4.6 [ required: >=0.4 ]
├── jinja2 3.1.2 [ required: >=3.0 ]
│   └── markupsafe 2.1.3 [ required: >=2.0 ]
├── markdown 3.3.7 [ required: >=3.2 ]
├── mkdocs 1.5.2 [ required: >=1.5.0 ]
│   ├── click 8.1.3 [ required: >=7.0 ]
│   ├── ghp-import 2.1.0 [ required: >=1.0 ]
│   │   └── python-dateutil 2.8.2 [ required: >=2.8.1 ]
│   │       └── six 1.16.0 [ required: >=1.5 ]
│   ├── jinja2 3.1.2 [ required: >=2.11.1 ]
│   │   └── markupsafe 2.1.3 [ required: >=2.0 ]
│   ├── markdown 3.3.7 [ required: >=3.2.1 ]
│   ├── markupsafe 2.1.3 [ required: >=2.0.1 ]
│   ├── mergedeep 1.3.4 [ required: >=1.3.4 ]
│   ├── packaging 23.1 [ required: >=20.5 ]
│   ├── pathspec 0.11.1 [ required: >=0.11.1 ]
│   ├── platformdirs 3.10.0 [ required: >=2.2.0 ]
│   ├── pyyaml 6.0.1 [ required: >=5.1 ]
│   ├── pyyaml-env-tag 0.1 [ required: >=0.1 ]
│   │   └── pyyaml 6.0.1 [ required: Any ]
│   └── watchdog 3.0.0 [ required: >=2.0 ]
├── mkdocs-material-extensions 1.1.1 [ required: >=1.1 ]
├── pygments 2.15.1 [ required: >=2.14 ]
├── pymdown-extensions 10.0.1 [ required: >=9.9.1 ]
│   ├── markdown 3.3.7 [ required: >=3.2 ]
│   └── pyyaml 6.0.1 [ required: Any ]
├── regex 2023.6.3 [ required: >=2022.4.24 ]
└── requests 2.31.0 [ required: >=2.26 ]
    ├── certifi 2023.7.22 [ required: >=2017.4.17 ]
    ├── charset-normalizer 3.1.0 [ required: <4,>=2 ]
    ├── idna 3.4 [ required: <4,>=2.5 ]
    └── urllib3 2.0.3 [ required: <3,>=1.21.1 ]
mkdocs-redirects 1.2.1 [ required: >=1.2.0 ]
└── mkdocs 1.5.2 [ required: >=1.1.1 ]
    ├── click 8.1.3 [ required: >=7.0 ]
    ├── ghp-import 2.1.0 [ required: >=1.0 ]
    │   └── python-dateutil 2.8.2 [ required: >=2.8.1 ]
    │       └── six 1.16.0 [ required: >=1.5 ]
    ├── jinja2 3.1.2 [ required: >=2.11.1 ]
    │   └── markupsafe 2.1.3 [ required: >=2.0 ]
    ├── markdown 3.3.7 [ required: >=3.2.1 ]
    ├── markupsafe 2.1.3 [ required: >=2.0.1 ]
    ├── mergedeep 1.3.4 [ required: >=1.3.4 ]
    ├── packaging 23.1 [ required: >=20.5 ]
    ├── pathspec 0.11.1 [ required: >=0.11.1 ]
    ├── platformdirs 3.10.0 [ required: >=2.2.0 ]
    ├── pyyaml 6.0.1 [ required: >=5.1 ]
    ├── pyyaml-env-tag 0.1 [ required: >=0.1 ]
    │   └── pyyaml 6.0.1 [ required: Any ]
    └── watchdog 3.0.0 [ required: >=2.0 ]
mkdocstrings-python 1.1.0 [ Not required ]
├── griffe 0.29.0 [ required: >=0.24 ]
│   └── colorama 0.4.6 [ required: >=0.4 ]
└── mkdocstrings 0.22.0 [ required: >=0.20 ]
    ├── jinja2 3.1.2 [ required: >=2.11.1 ]
    │   └── markupsafe 2.1.3 [ required: >=2.0 ]
    ├── markdown 3.3.7 [ required: >=3.3 ]
    ├── markupsafe 2.1.3 [ required: >=1.1 ]
    ├── mkdocs 1.5.2 [ required: >=1.2 ]
    │   ├── click 8.1.3 [ required: >=7.0 ]
    │   ├── ghp-import 2.1.0 [ required: >=1.0 ]
    │   │   └── python-dateutil 2.8.2 [ required: >=2.8.1 ]
    │   │       └── six 1.16.0 [ required: >=1.5 ]
    │   ├── jinja2 3.1.2 [ required: >=2.11.1 ]
    │   │   └── markupsafe 2.1.3 [ required: >=2.0 ]
    │   ├── markdown 3.3.7 [ required: >=3.2.1 ]
    │   ├── markupsafe 2.1.3 [ required: >=2.0.1 ]
    │   ├── mergedeep 1.3.4 [ required: >=1.3.4 ]
    │   ├── packaging 23.1 [ required: >=20.5 ]
    │   ├── pathspec 0.11.1 [ required: >=0.11.1 ]
    │   ├── platformdirs 3.10.0 [ required: >=2.2.0 ]
    │   ├── pyyaml 6.0.1 [ required: >=5.1 ]
    │   ├── pyyaml-env-tag 0.1 [ required: >=0.1 ]
    │   │   └── pyyaml 6.0.1 [ required: Any ]
    │   └── watchdog 3.0.0 [ required: >=2.0 ]
    ├── mkdocs-autorefs 0.4.1 [ required: >=0.3.1 ]
    │   ├── markdown 3.3.7 [ required: >=3.3 ]
    │   └── mkdocs 1.5.2 [ required: >=1.1 ]
    │       ├── click 8.1.3 [ required: >=7.0 ]
    │       ├── ghp-import 2.1.0 [ required: >=1.0 ]
    │       │   └── python-dateutil 2.8.2 [ required: >=2.8.1 ]
    │       │       └── six 1.16.0 [ required: >=1.5 ]
    │       ├── jinja2 3.1.2 [ required: >=2.11.1 ]
    │       │   └── markupsafe 2.1.3 [ required: >=2.0 ]
    │       ├── markdown 3.3.7 [ required: >=3.2.1 ]
    │       ├── markupsafe 2.1.3 [ required: >=2.0.1 ]
    │       ├── mergedeep 1.3.4 [ required: >=1.3.4 ]
    │       ├── packaging 23.1 [ required: >=20.5 ]
    │       ├── pathspec 0.11.1 [ required: >=0.11.1 ]
    │       ├── platformdirs 3.10.0 [ required: >=2.2.0 ]
    │       ├── pyyaml 6.0.1 [ required: >=5.1 ]
    │       ├── pyyaml-env-tag 0.1 [ required: >=0.1 ]
    │       │   └── pyyaml 6.0.1 [ required: Any ]
    │       └── watchdog 3.0.0 [ required: >=2.0 ]
    └── pymdown-extensions 10.0.1 [ required: >=6.3 ]
        ├── markdown 3.3.7 [ required: >=3.2 ]
        └── pyyaml 6.0.1 [ required: Any ]
```

mkdocs, copier, mike

**Comment by laixintao** [comment]
turns out that pdm's compatibility surprisingly good! I don't event need to change one single line.

**Review by frostming — APPROVED** [review]
LGTM 🎉

**Pull request merged**
