### PR TITLE
feat: rename the package-type config to distribution

### PR DESCRIPTION
**Pull request by frostming**
Signed-off-by: Frost Ming <me@frostming.com>

## Pull Request Checklist

- [ ] A news fragment is added in `news/` describing what is new.
- [ ] Test cases added for changed code.

### CODE REVIEW

**Comment by lmmx** [comment]
@frostming Cool, should this be updated in the docs section "Usage > Project > Library or Application"?

**Comment by electrocnic** [comment]
For some reason, I now get a weird error when I try to run `pdm install` in my existing project.
It worked fine with the old `package-type = "application"` and it would still work with that same line after my update from 3.11.1 to 3.12.1, but now when I use `distribution = "false"` I get:

image

with the log folder content:
```
pdm.termui: error: Multiple top-level packages discovered in a flat-layout: ['api', 'pages', 'stats', 'vuedj', 'contact', 'pricing', 'accounts', 'test_util'].
pdm.termui:
pdm.termui: To avoid accidental inclusion of unwanted files or directories,
pdm.termui: setuptools will not proceed with this build.
pdm.termui:
pdm.termui: If you are trying to create a single distribution with multiple packages
pdm.termui: on purpose, you should not rely on automatic discovery.
pdm.termui: Instead, consider the following options:
pdm.termui:
pdm.termui: 1. set up custom discovery (`find` directive with `include` or `exclude`)
pdm.termui: 2. use a `src-layout`
pdm.termui: 3. explicitly set `py_modules` or `packages` with a list of names
pdm.termui:
pdm.termui: To find more information, look for "package discovery" on setuptools docs.
```
My folder layout and packages and other stuff did not change.
What am I supposed to do to fix this?

For now, I left the old "application" string in my pyproject.toml.

**Comment by frostming** [comment]
@electrocnic distribution = false

without the quotes

**Comment by frostming** [comment]
Thanks, the auto fixer isn't behaving correctly.

Andreas Wiesinger ***@***.***> 于2024年1月21日周日 01:07写道：

**Comment by steakhutzeee** [comment]
I had the same issue and solved with that, thought the problem was with the fact i'm running an application and not a library and i had to remove the project name from pyproject.toml.

Is this still the case? Should project name be omitted? It actually works with the name, no version set, and  `distribution = false`

**Comment by deronnax** [comment]
to link things together: package-type was introduced in https://github.com/pdm-project/pdm/pull/2394.

**Pull request merged**
