### PR TITLE
fix: Exclude `packaging 22.0` to avoid breakage

### PR DESCRIPTION
**Pull request by frostming**
## Pull Request Check List

- [x] A news fragment is added in `news/` describing what is new.
- [ ] Test cases added for changed code.

## Describe what you have changed in this PR.

It resolves the following issues, while still allows future packaging versions to be installed

- #1556
- #1558

### CODE REVIEW

**Comment by ferminho** [comment]
Hi there, won't this happen again if packaging releases another version?

**Comment by ferminho** [comment]
I might not have the full picture of the issue and I'd indeed like future updates. I simply asked to understand if we could face the same issue when, say, packaging 22.1 is released.
If so, the recommendation is to pin packaging in our side in every project? 

Honest questions, no intention to debate. Thanks a lot for your support!

**Comment by franzhaas** [comment]
@ferminho 
There is a discussion about how to have repeatable deployments of pdm over there.: https://github.com/pdm-project/pdm/issues/1558

**Comment by pawamoy** [comment]
> If so, the recommendation is to pin packaging in our side in every project?

Locally, you probably have a single installation of PDM. In that case you could simply restrict its `packaging` dependency to exclude the new, unsupported version of packaging, until PDM excludes it itself or becomes compatible with it.
In CI, you'll need to add an instruction to your steps/workflow to restrict it as well, until, again, PDM excludes or supports it.

**Comment by ferminho** [comment]
> Locally, you probably have a single installation of PDM. In that case you could simply restrict its `packaging` dependency to exclude the new, unsupported version of packaging, until PDM excludes it itself or becomes compatible with it. This will fix it for all of your local projects.

We have recently adopted pdm as our standard package manager and we have many installations in Python services, libraries and also environments such as JupyterLab or Databricks. This is why the issue created a bit of havoc everywhere when an old, unused version of [pyzqm](https://github.com/zeromq/pyzmq) couldn't be parsed as candidate. 

Thanks! moving to the other conversation

**Comment by frostming** [comment]
> This is why the issue created a bit of havoc everywhere when an old, unused version of [pyzqm](https://github.com/zeromq/pyzmq) couldn't be parsed as candidate.

If this is what blocks you, it has been already solved by the latest version of `unearth`, those legacy illegal packages will be skipped.

**Comment by lyz-code** [comment]
@frostming can you please make a release with this fix? all my CI pipelines will thank you for it

**Pull request merged**
