### PR TITLE
ignore typing in functions that index distlib.metadata._data

### LINKED ISSUE #334: pdm.models.project_info.ProjectInfo is weakly-typed
this is currently an un-typed dictionary. This leads to a bunch of mypy errors-

```
pdm run mypy pdm | grep project_info                                                                                                       1 ✘  5s 
pdm/models/project_info.py:17: error: Incompatible types in "yield" (actual type "Tuple[str, Union[str, List[str]]]", expected type "Tuple[str, str]")
pdm/models/project_info.py:18: error: Incompatible types in "yield" (actual type "Tuple[str, Union[str, List[str]]]", expected type "Tuple[str, str]")
pdm/models/project_info.py:23: error: Incompatible types in "yield" (actual type "Tuple[str, Union[str, List[str]]]", expected type "Tuple[str, str]")
pdm/models/project_info.py:25: error: Item "str" of "Union[str, List[str], Dict[<nothing>, <nothing>]]" has no attribute "get"
pdm/models/project_info.py:25: error: Item "List[str]" of "Union[str, List[str], Dict[<nothing>, <nothing>]]" has no attribute "get"
pdm/models/project_info.py:25: error: No overload variant of "get" of "Mapping" matches argument types "str", "Dict[<nothing>, <nothing>]"
pdm/models/project_info.py:25: note: Possible overload variant:
pdm/models/project_info.py:25: note:     def [_T] get(self, key: <nothing>, default: _T) -> _T
pdm/models/project_info.py:25: note:     <1 more non-matching overload not shown>
pdm/models/project_info.py:28: error: Need type annotation for 'author_contact'
pdm/models/project_info.py:33: error: Incompatible types in "yield" (actual type "Tuple[str, Union[str, List[str]]]", expected type "Tuple[str, str]")
pdm/models/project_info.py:34: error: Item "str" of "Union[str, List[str], Dict[<nothing>, <nothing>]]" has no attribute "get"
pdm/models/project_info.py:34: error: Item "List[str]" of "Union[str, List[str], Dict[<nothing>, <nothing>]]" has no attribute "get"
pdm/models/project_info.py:34: error: No overload variant of "get" of "Mapping" matches argument types "str", "Dict[<nothing>, <nothing>]"
pdm/models/project_info.py:34: note: Possible overload variant:
pdm/models/project_info.py:34: note:     def [_T] get(self, key: <nothing>, default: _T) -> _T
pdm/models/project_info.py:34: note:     <1 more non-matching overload not shown>
pdm/models/project_info.py:37: error: Incompatible types in "yield" (actual type "Tuple[str, Union[str, List[str]]]", expected type "Tuple[str, str]")
pdm/models/project_info.py:38: error: Incompatible types in "yield" (actual type "Tuple[str, Union[str, List[str]]]", expected type "Tuple[str, str]")
pdm/models/project_info.py:42: error: Incompatible types in "yield" (actual type "Tuple[str, Union[str, List[str]]]", expected type "Tuple[str, str]")
pdm/models/project_info.py:43: error: Incompatible types in "yield" (actual type "Tuple[str, Union[str, List[str]]]", expected type "Tuple[str, str]")
pdm/models/project_info.py:48: error: Incompatible types in "yield" (actual type "Tuple[str, Union[str, List[str]]]", expected type "Tuple[str, str]")
pdm/models/project_info.py:49: error: Incompatible types in "yield" (actual type "Tuple[str, Union[str, List[str]]]", expected type "Tuple[str, str]")
pdm/models/project_info.py:50: error: Incompatible types in "yield" (actual type "Tuple[str, Union[str, List[str]]]", expected type "Tuple[str, str]")
pdm/models/project_info.py:51: error: Incompatible types in "yield" (actual type "Tuple[str, Union[str, List[str]]]", expected type "Tuple[str, str]")
pdm/models/project_info.py:52: error: Incompatible types in "yield" (actual type "Tuple[str, Union[str, List[str]]]", expected type "Tuple[str, str]")
pdm/models/project_info.py:55: error: Incompatible types in "yield" (actual type "Tuple[str, Union[str, List[str]]]", expected type "Tuple[str, str]")
pdm/models/project_info.py:57: error: Item "None" of "Union[str, List[str], None]" has no attribute "__iter__" (not iterable)
```

this can be improved by using a strongly-typed data structure instead

### PR DESCRIPTION
**Pull request by danieleades**
closes #334

**this change wipes out 28 mypy errors.**

this is justified on the basis that the datastructure being indexed is `distlib.metadata._data`, and the structure is relatively stable.

### CODE REVIEW

**Comment by danieleades** [comment]
tests are failing on python3.7 + ubuntu-latest.
that's odd.

**Comment by frostming** [comment]
Can you help do `pdm update pdm-pep517` and push the change? This should fix the failure

**Comment by danieleades** [comment]
> Can you help do `pdm update pdm-pep517` and push the change? This should fix the failure

to be rebased on #336

**Comment by frostming** [comment]
All should get back to green now

**Comment by danieleades** [comment]
rebased

**Comment by frostming** [comment]
@danieleades Thanks a bunch for your contributions on PDM project, would you like to be a collaborator for this project? I didn't find your email or other contacts so reply here.

**Comment by danieleades** [comment]
> @danieleades Thanks a bunch for your contributions on PDM project, would you like to be a collaborator for this project? I didn't find your email or other contacts so reply here.

Sorry for taking so long to respond, it's been a busy week. i'd love to help where I can! I don't much mind whether that's as a collaborator or just by throwing the odd pull request at you.
Being a collaborator increases the chances that i'll accidentally modify the `_vendor/` directory again ;)

**Pull request merged**
