### PR TITLE
feat: accept --ignore-remembered in pdm init

### PR DESCRIPTION
**Pull request by eltoder**
Closes: #1672

### CODE REVIEW

**Comment by eltoder** [comment]
A simpler alternative is to always pass `ignore_remembered=False` in init, if this is acceptable.

**Comment by frostming** [comment]
Thanks, can you modify to always ignore remembered?

**Comment by eltoder** [comment]
@frostming done, please take a look

**Comment by frostming** [comment]
Please also fix the test case `tests/cli/test_init.py::test_init_non_interactive`

**Comment by eltoder** [comment]
Sorry, missed that. Fixed now.

**Pull request merged**
