### PR TITLE
feat: set project root env

### PR DESCRIPTION
**Pull request by ZeeD**
## Pull Request Checklist

- [x] A news fragment is added in `news/` describing what is new.
- [ ] Test cases added for changed code.

## Describe what you have changed in this PR.

Expose `PROJECT_ROOT` as an env variable during script runs

fixes https://github.com/pdm-project/pdm/issues/2993

### CODE REVIEW

**Comment by frostming** [comment]
Why not just inject the env into the `process_env` when running processes?

https://github.com/pdm-project/pdm/blob/61657a4b97b5225b5c7d3373df868ea19e371dd9/src/pdm/cli/commands/run.py#L258

You won't contaminate the global_options in this way.

**Comment by frostming** [comment]
Oh, the project root is already exposed via `PDM_PROJECT_ROOT` env.

https://github.com/pdm-project/pdm/blob/c190e1439cf88cfa06bbf20ee01b1f0d6dfeabbb/src/pdm/environments/base.py#L80

If no objection, i will close this PR.

**Comment by ZeeD** [comment]
> Why not just inject the env into the `process_env` when running processes?
> 
> https://github.com/pdm-project/pdm/blob/61657a4b97b5225b5c7d3373df868ea19e371dd9/src/pdm/cli/commands/run.py#L258
> 
> You won't contaminate the global_options in this way.

Yeah, I may try this approach instead


> Oh, the project root is already exposed via `PDM_PROJECT_ROOT` env.
> 
> https://github.com/pdm-project/pdm/blob/c190e1439cf88cfa06bbf20ee01b1f0d6dfeabbb/src/pdm/environments/base.py#L80
> 
> If no objection, i will close this PR.

I didn't knew about `PDM_PROJECT_ROOT`, I may have missed it in the docs, sorry.

But, while invoking directly a script I see that `PDM_PROJECT_ROOT` is available, it seems to me that in the `.env` variable expansion it doesn't work: let's say that I have

`pyproject.toml`:
```toml
[tool.pdm.scripts]
_.env_file = ".env"
var1 = { shell = "echo $VAR1" }
var2 = { shell = "echo $VAR2" }
var3 = { shell = "echo $PDM_PROJECT_ROOT" }
```

`.env`
```properties
VAR1 = "VAL1"

VAR2 = "VAR1=${VAR1}; USER=${USER}; PDM_PROJECT_ROOT=${PDM_PROJECT_ROOT};"
````

`pdm run` have some unexpected behaviour:


```bash
$ pdm run var1
VAL1
$ pdm run var2
VAR1=VAL1; USER=<my username>; PDM_PROJECT_ROOT=;
$ pdm run var3
<current directory
$ 
```

it seems that the definition of the `PDM_PROJECT_ROOT` env variable occurs "too late" to let `dotenv` enrich the `.env` file parsing.

Do you think it would be possible to move the `PDM_PROJECT_ROOT` before the evaluation of the `_.env` file during the execution of the run?

**Comment by frostming** [comment]
> it seems that the definition of the `PDM_PROJECT_ROOT` env variable occurs "too late" to let `dotenv` enrich the `.env` file parsing.

Not only that, all additional env vars are not inject into `os.environ` to make `dotenv` be aware of.

**Comment by ZeeD** [comment]
searching for `PDM_PROJECT_ROOT` I've found #1324 
Do you think that my use case - as you can see in #2993 - could be solved changing the behavior of `pdm`?

**Comment by frostming** [comment]
This is superseded by #3087 thanks anyway

**Comment by ZeeD** [comment]
thanks to you for the update!

**Pull request closed without merging**
