### PR TITLE
Change default value of `find_project_root()`

### PR DESCRIPTION
**Pull request by drunkwcodes**
## Pull Request Checklist

- [ ] A news fragment is added in `news/` describing what is new.
- [ ] Test cases added for changed code.

## Describe what you have changed in this PR.

Currently, if `find_project_root()` fails to find a root, it returns `None`.
It is inconvenient for `Path(find_project_root())`, which needs `os.PathLike` str instead of Optional[str].

`None` is not welcome in here.

So I change the function to have a `default` kwarg that will be returned when the root was not found.

### CODE REVIEW

**Comment by frostming** [comment]
This changes the behavior, see the CI failure. Sometimes we do want to know a project root can't be found. To make the type check, there are two options:

1. Raise an error instead of return None, so that we can know the project root can't be found. And in certain cases you can assume it always succeeds.
2. Make two signatures with `typing.overload`, when default isn't given it is the same as the current behavior, returning `str | None`, and if default is a string value, it will always return a `str`.

**Comment by drunkwcodes** [comment]
@frostming Thanks for your quick reply.

I have a solution now.
It can tell us the root is not found by assuring return value is Path(".") and not absolute.

If it finds root, it will be absolute path. There is a subtle difference.

**Comment by frostming** [comment]
> @frostming Thanks for your quick reply.
> 
> I have a solution now. It can tell us the root is not found by assuring return value is Path(".") and not absolute.
> 
> If it finds root, it will be absolute path. There is a subtle difference.

We need a more obvious difference to distinguish the two cases. `str | None`, or `success | exception`

**Comment by drunkwcodes** [comment]
@frostming If so, I think `None` is better. Current function is good.

But we can gain the `Path()` compatibility by this PR.
I fixed the Project initialization.
It works perfect now.

Is the obvious difference really needed?

**Comment by frostming** [comment]
Comparing to `Path(".")` to detect a failing path is not good to me.
Why not take either option I mentioned above, it should solve your problem.

**Comment by drunkwcodes** [comment]
@frostming As I mentioned, `None` is not compatible with `Path()`.
And an exception is exaggerating. 

So I decide to leave the function as it is.
But I kept my branch in my fork.
If you change your mind in some day, I will re-open this PR.

**Comment by frostming** [comment]
@drunkwcodes You may not understand my suggestion:

```python
def find_project_root(cwd: str = ".", max_depth: int = 5, default: str | None = None) -> str | None:
     ...
```

When `default` is not given, it is the same as the current behavior, but when it is given a string, `Path(find_project_root(default="."))` is just happy with it. You can even achieve this by `Path(find_project_root() or ".")`

I don't think there is any other problem with it.

**Comment by drunkwcodes** [comment]
OK, it sounds promising.

I will take some time to make this change,
see you next time!

**Comment by drunkwcodes** [comment]
But I think mypy will not happy with this. 
Fine. There is no `Path(find_project_root())` usage.

**Comment by frostming** [comment]
> But I think mypy will not happy with this.

It will, use `@typing.overload`

**Comment by drunkwcodes** [comment]
@frostming I'm not experienced with `overload`.

Please add that for me.

Do you mean:

```python
from typing import overload

@overload
def find_project_root(cwd: str = ".", max_depth: int = 5, default: str) -> str:
     ...
```

**Comment by frostming** [comment]
```
from typing import overload

@overload
def find_project_root(cwd: str = ".", max_depth: int = 5, default: None = ...) -> str | None:
     ...

@overload
def find_project_root(cwd: str = ".", max_depth: int = 5, default: str = ...) -> str:
     ...

def find_project_root(cwd: str = ".", max_depth: int = 5, default: str | None = None) -> str | None:
    # the implementation goes here
```

But I wonder why you are not fine with `Path(find_project_root() or ".")` ?

**Comment by frostming** [comment]
Okay, mypy isn't happy, can you answer this question?

> But I wonder why you are not fine with `Path(find_project_root() or ".")` ?

**Comment by drunkwcodes** [comment]
@frostming I didn't think about that.

And mypy complains: `src/pdm/utils.py:79: error: Overloaded function signatures 1 and 2 overlap with incompatible return types  [misc]
Found 1 error in 1 file (checked 108 source files)`.

So I think your workaround is the best answer. I'm going to close this PR.

**Pull request closed without merging**
