### PR TITLE
Use a new approach of cross-platform resolution

### PR DESCRIPTION
**Pull request by frostming**
## Pull Request Check List

- [x] A news fragment is added in `news/` describing what is new.
- [x] Test cases added for changed code.

### CODE REVIEW

**Comment by s0undt3ch** [comment]
Sadly what appealed to me, multiplatform requirements, is now gone.

**Comment by frostming** [comment]
@s0undt3ch Can you elaborate on what you said?

**Comment by s0undt3ch** [comment]
I meant the export to requirements files.
It's now platform dependent right?

**Comment by frostming** [comment]
yes, it is stated in the changelog:
`pdm export` no longer produces requirements file applicable for all platforms due to the new approach.

**Pull request merged**
