### PR TITLE
Add pyright/eglot config for emacs

### PR DESCRIPTION
**Pull request by pakelley**
## Pull Request Checklist

- [x] A news fragment is added in `news/` describing what is new.
- [N/A] Test cases added for changed code.

## Describe what you have changed in this PR.
MS's python lang server (as well as lsp-python-ms) are archived in favor of pyright. Additionally, eglot will be packaged with Emacs once Emacs 29 is released.

### CODE REVIEW

**Comment by pakelley** [comment]
Adding a news fragment now...

**Comment by pakelley** [comment]
Also, I'm curious why Emacs's config is in a different section than all of the other editors? If it's arbitrary I'd be happy to move it.

**Comment by pakelley** [comment]
Sorry for the noise, but the config listed for Neovim works for Emacs too. If it seems helpful, I could add a note about doing it that way to the Emacs section, since it may be simpler in some cases.

**Comment by frostming** [comment]
@pakelley I am not an expert of emacs and I have no objections about the changes.

**Comment by pakelley** [comment]
Sounds good, well if you don't mind I'll move the emacs section next to the other editors and add a section about configuring via `pyproject.toml`.
Thanks for all of your work on pdm, it's the first python package management tool I've used that isn't painful :)

**Comment by pakelley** [comment]
Alright, as long as you're happy with this, I've made all of the changes I wanted. Let me know if there's anything you'd like updated.

**Review by frostming — APPROVED** [review]
LGTM

**Pull request merged**
