### PR TITLE
Replace bitwise AND with logical AND (which is breaking my use of UV)

### PR DESCRIPTION
**Pull request by theNewFlesh**
## Pull Request Checklist

- [ ] A news fragment is added in `news/` describing what is new.
- [ ] Test cases added for changed code.

`uv.py` uses bitwise and (&) for logic in which logical and (and) is required. When using UV with PDM, PDM throws a TypeError on these lines. This change resolves that.

### CODE REVIEW

**Review by frostming — COMMENTED** [review]
because that is not a logical and, that is an intersection operation. can you show how would it raise typeerror when both sides are not None?

**Comment by theNewFlesh** [comment]
I am looking for the error in my logs.

It was something like:
`TypeError: unsupported operand type(s) for &: Marker and bool`

I ran some test code to see if bitwise AND gives the same error and it does.

I'll post the error if I can find it.

**Comment by theNewFlesh** [comment]
Well I'm not finding it in the logs, but I found an old search I performed on the exact error:

`unsupported operand type(s) for &: 'Marker' and 'bool'`

On line 192 I believe.

I am switching over some existing projects from vanilla PDM to PDM with UV. Most have worked fine, but one often throws this error when I `pdm sync`.

**Comment by clement-tourriere** [comment]
Hello, I have the exact same error. Sadly I can't really provide an easy reproductible scenario, but from the code I guess there is parenthesis missing:

```
parent_marker & (marker or get_marker("")).is_empty()
```
raises the error: `*** TypeError: unsupported operand type(s) for &: 'Marker' and 'bool'`

but 
```
(parent_marker & (marker or get_marker(""))).is_empty()
```
works well.

I guess the fix could be something like:

```
        def marker_match(marker: Marker | None) -> bool:
            return not ((parent_marker & (marker or get_marker(""))).is_empty())
```

**Comment by frostming** [comment]
> Hello, I have the exact same error. Sadly I can't really provide an easy reproductible scenario, but from the code I guess there is parenthesis missing:

Thank you, you found the real bug! Too many parentheses made me overlook it.

**Pull request closed without merging**
