### PR TITLE
Feature: Signals for init, install, lock

### LINKED ISSUE #798: Support hooks for some basic operations
## Is your feature request related to a problem? Please describe.

This will benefit plug-ins for custom behaviors. #789 could be implemented using this feature

## Describe the solution you'd like

Some hooks or signals that come to my mind:

- post_init (args: project)
- pre_lock (args: project, requirements set to resolve)
- post_lock (args: project, resolved candidates map)
- pre_install (args: project, candidates to install)
- post_install (args: project, working_set)

To ensure the build is tool-agnostic, we deliberately exclude build hooks

### PR DESCRIPTION
**Pull request by frostming**
## Pull Request Check List

- [x] A news fragment is added in `news/` describing what is new.
- [x] Test cases added for changed code.

## Describe what you have changed in this PR.
Close #798

### CODE REVIEW

**Comment by frostming** [comment]
@pawamoy Added an API reference doc with `mkdocstrings`, nice done!

**Comment by pawamoy** [comment]
@frostming thanks :slightly_smiling_face: 
I think the latest version of pytkdocs removed these useless warnings, but mkdocstrings does not accept it yet. Let me check.

**Comment by frostming** [comment]
OK, i will merge this first, and we can upgrade mkdocstrings later

**Comment by pawamoy** [comment]
I just released mkdocstrings 0.17.0, let me know how it goes.

**Pull request merged**
