### PR TITLE
docs(publish): add note on PyPI API tokens in docs/usage/publish.md

### PR DESCRIPTION
**Pull request by vvanglro**
## Pull Request Checklist

- [ ] A news fragment is added in `news/` describing what is new.
- [ ] Test cases added for changed code.

### CODE REVIEW

**Comment by vvanglro** [comment]
```sh
pdm publish --help  
  -u USERNAME, --username USERNAME
                        The username to access the repository [env var: PDM_PUBLISH_USERNAME]
  -P PASSWORD, --password PASSWORD
                        The password to access the repository [env var: PDM_PUBLISH_PASSWORD]
```
The tips here should perhaps be changed as well?

**Comment by frostming** [comment]
Oh, so the username and password are no longer allowed to publish package? Then it needs to be updated.

**Comment by vvanglro** [comment]
I'm still looking for news that pypi is officially not supporting username and password release packages, but haven't found it yet. Instead, I'm running into a lot of the same problems with what appears to be pypi's unpublished instructions?

**Comment by frostming** [comment]
> I'm still looking for news that pypi is officially not supporting username and password release packages, but haven't found it yet. Instead, I'm running into a lot of the same problems with what appears to be pypi's unpublished instructions?

That's fine, but some private pypi instances may still allow username and password

**Comment by vvanglro** [comment]
It seems that after turning on 2FA, you must use a token to publish.

https://discuss.python.org/t/announcement-2fa-now-required-for-pypi/42251/4

**Comment by vvanglro** [comment]
> That's fine, but some private pypi instances may still allow username and password. I think it's fine to make it default to `__token__` for now.

We pointed out in the docs that if you want to publish the package to the official pypi, you must use the token method.

**Comment by vvanglro** [comment]
Or cli adds an api token option to differentiate from username/password.🤔

**Pull request merged**
