### PR TITLE
rename project from Python Development Master to Python Development Manager

### PR DESCRIPTION
**Pull request by burnettk**
I was researching tools in this area today, like pipenv, poetry, and pdm. I was excited about pdm potentially being faster for my use case (I've seen the benchmarks). I was a little surprised by the name. It seems like folks are trying to avoid the word "master" these days (see https://www.vice.com/en/article/8x7akv/masterslave-terminology-was-removed-from-python-programming-language and similar articles). It seemed like it might be easy to change, and the word "Manager" might better explain what the tool does anyway. Thanks for your great open source project!

### CODE REVIEW

**Comment by frostming** [comment]
I am okay with this change, can you please add a news fragment to the `news` folder?

**Comment by pawamoy** [comment]
Please no. There is nothing wrong with the word master. Just don't do something because others did. Ultimately that's your decision @frostming but I'd be really sad to see this change happen. Please at least gather feedback from the community first.

**Comment by burnettk** [comment]
I added a fragment to the `news` folder. I agree that there was never any harm intended by the project authors. I agree I'm privileged. I agree that I'm just hoping the world is a better place as a result of this change, and not certain that it actually helps in a concrete way. I certainly hope that it doesn't hurt this project. Thanks for all of your contributions to open source, @pawamoy, and I'm sorry we had to meet under these circumstances. With respect.

**Comment by pawamoy** [comment]
Thank you for your thoughtful answer @burnettk. You conveyed the things I wanted to express. I have absolutely no grudge against you of course, I simply wanted to make sure we can all discuss this before anything is merged (well, things can be reverted if needed).

I still want to emphasize that there's nothing wrong with the word master, and that if the project name is changed, it should be because of stylistic reasons, which I would be totally fine with. But then I'd argue that "Python Development Manager" doesn't make much sense. If @frostming wants to go with manager instead of master, then we should go all the way and change development with dependency or package (though package wouldn't match the D in PDM).

As for the current name: I find it pretentious, and I like it. It shows the ambition of the project, as if by using it, you become a Python Development Master. "Python Dependency Manager", though accurate, sounds a bit dull, and that's fine too (lots of project bear the very name of what they do). I think the current name became part of the identity of the project in some way. Changing it should be made with care.

**Comment by frostming** [comment]
Thanks for your thoughtful words from both sides. I said "ok" just because I have no objections for either word - "manager" is also used many times in the README and documentation. Changing it only affects the subtitle in PyPI page and related places on the documentation site. I myself also had a hard time thinking of a good name for this project and I don't think "pdm" is one of them. So @pawamoy thank you for letting me know people care about the name and love it.

If this is the case, keeping the name as it is now may be a good idea.

**Comment by ohlol** [comment]
I agree with @daylinmorgan. Grammatically, the use of "master" doesn't really make sense.

**Comment by lyz-code** [comment]
I'd also prefer to avoid the `master` word as much as possible. There are a lot of people doing the change in their repositories after being discussed in many different forums. I don't see the issue being raised by privileged people as we would not even notice the is an issue using the word. 

So if the change is not expensive, and it makes the life easier for some people, I'd say go for it.

**Comment by pawamoy** [comment]
I was hoping we could stay on the aesthetic side of things.

> I'd also prefer to avoid the master word as much as possible. There are a lot of people doing the change in their repositories after being discussed in many different forums.

That is, again, a non-argument. For all I know, these "lot of people" did the change for the same reason: "others did". Also, please add links to these many different forums. We are discussing it here, and it doesn't mean the change will happen, or the change is a good thing. I'd like to see *why* they did the change exactly (and you should too).

> I don't see the issue being raised by privileged people as we would not even notice there is an issue using the word.

Well I find that insulting. Being privileged has nothing to do with being aware/unaware of societal/systemic issues affecting non-dominant groups, and with being active or passive in bringing solutions. Privileged people can perfectly be aware of issues, or even raise them.

Finally, and this is the most important point to me: there *isn't* an issue with using the word master! That is another blank statement. Please explain *what* exactly the issue is.

> if it makes the life easier for some people

Again, can you explain *who* are these people, and *how* it makes their lives easier?
You can of course choose not to answer, and let the conversation continue on the aesthetic part.

**Comment by lyz-code** [comment]
Hi, 

> That is, again, a non-argument. For all I know, these "lot of people" did the change for the same reason: "others did". Also, please add links to these many different forums. 

After a quick search I found that the first one to do the change was [the software freedom conservancy with the Git project](https://sfconservancy.org/news/2020/jun/23/gitbranchname/). You can also see [Python](https://www.vice.com/en/article/8x7akv/masterslave-terminology-was-removed-from-python-programming-language) and [Github](https://www.theserverside.com/feature/Why-GitHub-renamed-its-master-branch-to-main)'s statements. If you read them, you'll see that none has done it because others were doing it, each one says that the motivation of the change relies on that *`master` is offensive to some people and we empathize with those hurt by the use of that term*.

> I'd like to see why they did the change exactly (and you should too)

It probably was not your intention, but by saying `and you should too` I've felt patronized, as if you were in possession of some knowledge that I don't or on a higher moral position. Please don't assume that I haven't given a deep thought to the issue before starting the "painful" process of changing all my repositories.

> Well I find that insulting. Being privileged has nothing to do with being aware/unaware of societal/systemic issues affecting non-dominant groups, and with being active or passive in bringing solutions. 

My statement was not meant to be insulting, sorry if I made you feel so. It's a lesson I learned on my own skin throughout the years. The fact that I have not suffered an oppression on myself makes me blind to it's effects. There are thousand of situations, gestures, double meaning words and sentences that went unnoticed by me until I started discussing it with the people that are suffering them (women, racialized people, LGTBQI+, ...). Throughout my experience I've seen that the more privileged you are, the blinder you become. You can read more on privileged blindness [here](https://iveybusinessjournal.com/fighting-privilege-blindness/), [here](https://dojustice.crcna.org/article/becoming-aware-my-privilege) or [here](https://www.mindful.org/the-research-on-white-privilege-blindness/) (I've skimmed through the articles, and are the first articles I've found, there are probably better references). 

>  Privileged people can perfectly be aware of issues, or even raise them.

That doesn't mean that we don't see any of them. I agree with you that privileged people can be aware of some issues, and the more you read, discuss and train yourself, the better you'll detect them. All I'm saying is that a non privileged person will always detect more because they suffer them daily.

> Finally, and this is the most important point to me: there isn't an issue with using the word master! 

I understand that for you there is no issue using the word *master*, there wasn't an issue for me either until I saw these projects doing the change, again I was blinded to the issue as I'm not suffering it. That's because change is not meant for us, as we're not triggered by it. The change is targeted to the people that do perceive that `master` is an offensive term. What we can do is empathize with them and follow this tiny tiny tiny gesture. It's the least we can do.

Think of a term that triggers you, such as *heil hitler*, imagine that those words were being used to define the main branch of your code, and that everyday you sit in front of your computer you see them. You'll probably be reminded of the historic events, concepts, feelings that are tied to that term each time you see it, and being them quite negative it can slowly mine you. Therefore it's legit that you wouldn't want to be exposed to that negative effects.

> can you explain who are these people

Probably the *some people* term refers to people that belongs to communities that are and have been under constant oppression for a very long time, in this case, specially the racialized ones which have suffered slavery.

Sadly you will probably won't hear any of the people that are affected in this pull request, first because there are not that many, sadly the IT world is dominated by middle aged, economically comfortable, white, cis, males, and small changes like this are meant to foster diversity in the community by allowing them being more comfortable. Secondly because when they see these debates they move on as they are so fed up on teaching privileged people of their privileges, they not only have to suffer the oppression, we also put the burden on their shoulders to
teach us.

As and ending thought, it surprised me and you (from I understood of your last words) how deeply you care of the change. In my experience that discomfort feeling and strong reactions over a "small" change are characteristic of privileged people that feel that their privileges are being threatened, I've felt them myself countless times. When I feel it, I usually do two things, fight them as strong as I can, or embrace them, analyze them, and go to the root of them. Depending on how much energy I have I go with the easy or the hard one. I'm not saying that it's you're case, but it could be.

I've done my best to show how I understand what exactly the issue is, who are these people, and how it would make their lives easier. If there is anything you feel is left unanswered or there's something I haven't explained well, we can go on with the conversation :)

**Comment by pawamoy** [comment]
Hi again,

> It probably was not your intention, but by saying and you should too I've felt patronized

My sincere apologies. I was indeed not trying to assume anything about you. If I had to rephrase, I would say "and you should too, **whether you already know why they did, or not**. That was poorly formulated, sorry. The rephrasing is probably not much better either.

> Being privileged has nothing to do with being aware/unaware

I knew I was in trouble for saying that "it has nothing to do with [...]". I knew about privileged blindness, but wouldn't have able to put a name on it, so there definitely are many things I can learn about it. Thank you for the links. Now, I was quick to write that, but that was in opposition to your own sentence that was conveying the idea that it was impossible that privileged people could raise that issue. I shouldn't have used "insulting" either, maybe "dismissing of possibilities" would have been better.

> I understand that for you there is no issue using the word master

My whole point is that there is a big difference between the word master alone, and the word master used in conjunction with slave. Context is very important, because when you read or listen about something, you are in a particular setting, or context, and of all the meanings a word can take depending on the context, usually only one will come to mind. In PDM's context, there's only the word "master", and not the word "slave". That difference is illustrated by the links you posted: they all relate to the master/slave use, except maybe for the GitHub statement, though I remember at the time that people had found that "master" was initially used in git in relation with "slave", and that was why it was problematic. One link I found, but there are others:  https://mail.gnome.org/archives/desktop-devel-list/2019-May/msg00066.html
That's the only reason why I'm not keen on replacing master here, in PDM's context. And because I have an idea on how dangerous it can be to erase words from vocabulary (a bit extreme branch of the conversation perhaps... 1984 did leave a mark on me).

Now, something I might have missed is that, for some people maybe the trauma is important enough that the context becomes irrelevant. I accept that. I'm imagining for example that, if one day butterflies are responsible for a global traumatic event, then of course it would be ill-advised to use "butterfly" or "butterflies" for the names of projects that are not directly related to that event, since it would potentially hurt people and would therefore make the project's community unwelcoming to them. At the same time, I have trouble accepting blindly that master should be replaced, because, as stated before, I was never able to find a study that shows it actually hurts, whatever the context, some people or some communities, and because it has so many valid uses: chess master/grandmaster, martial art master/grandmaster, masters degree (I'm a computer science master, because I mastered computer science according to my university standards), Python Development Master :wink:, etc. If we were to replace it here, should we replace it there as well? Should we also replace it in other languages? In France, teachers are called Maitre and Maitresse in elementary schools. Generally speaking, a master is someone who knows something well enough to teach it. Should we rename these titles? Or should we only care about particular cultures? Are we trying to find some kind of a lowest common denominator list of words that are not controversial? Real questions :slightly_smiling_face: 

I will not expand on the other points you made: I totally agree with them.

> I've done my best to show how I understand what exactly the issue is, who are these people, and how it would make their lives easier. If there is anything you feel is left unanswered or there's something I haven't explained well, we can go on with the conversation :)

Thank you for taking the time to write back. I am very glad you answered.

**Comment by lyz-code** [comment]
Hi once again,

> My sincere apologies. 

Don't worry about it, thank you anyway for the apology.

> My whole point is that there is a big difference between the word master alone, and the word master used in conjunction with slave.

I see your point, it's sketchy where to put the line, hence all the discussions around this topic.

> I was never able to find a study that shows it actually hurts, whatever the context, some people or some communities

Sadly these kind of issues are not often covered by studies, as they are not interesting for the companies, and usually are carried out by independent collectives, which won't focus on exactly the word master in itself, but a broader idea on how does the language shape our thoughts, emotions and relationships. You can find a lot of bibliography on that. Just to mention an example, the feminist movement has pushed a lot "lately" to change how we use the language to make it more inclusive.

Also, I don't think we need a study to support each and every one of our decisions, it would be nice, but it may lead to inaction due to blocks and delays.

>  it has so many valid uses: chess master/grandmaster, martial art master/grandmaster, masters degree (I'm a computer science master, because I mastered computer science according to my university standards)

I haven't thought of these terms, and now that I do, the term master on chess, martial arts or any other ability still feels a little bit bragging, as if you were saying, I know it all about X, which again puts you in a higher position over the rest of the people that don't master it. I'm aware that it's a super subjective point of view, and as I'm not an english native speaker, the official meaning may be other. Still is how I perceive the term. Grandmaster is even worse xD. Experienced chess player, professional chess player feels better for me. In masters degree, the word is not alone so I guess it would be more difficult that it is taken as a trigger word, although university degree may reflect better the concept. I'm not saying that we should erase master from our language, but if other words express better the concept, why stick with the one that we're using just because is the one we've always used?

This point is perfectly represented in Python Development Master, as a user of `pdm` I may have read the term the first time I browsed the documentation, but after, for me it was just `pdm`. And now that I've used it for a while, I still don't understand what does Python Development Master mean. As far as I've understood is a package and dependency manager, whereas developing involves much many other concepts. If it were Package Manager Master I'd understand your point here, but in the context it's used I feel that as @burnettk has said, manager is a word that defines better the program, and for me Python Dependency Manager could be the perfect name (although I know it does much more than that).

Thank you too for the exchange and for your careful writing :)

**Comment by frostming** [comment]
Due to the arguments that happened here, I wonder whether it is a good idea to leave out the Python Development Master from the tagline, and use something more specific instead, like "A modern Python package manager with PEP 582 support."(The same as the project description). And if someone is curious about the origin of the name which looks like an abbreviation, there will be a section "What does PDM mean" in the README, explaining what it used to be and what each letter represents.

**Comment by 1oglop1** [comment]
Hi, lemme add a little bit to this.
I'm not a great PC and English is my 2nd language. 
My first association with the word master [is being good at something](https://dictionary.cambridge.org/dictionary/english/master) and which PDM certainly is. 
It also comes as the second explanation from the Cambridge dictionary page.

I kept the word `PDM` in my memory and then when I was searching for this project I could not find it.
And my second search term was `pdm python package manager` - which came quite naturally because I made an association that it is similar to `npm`. 
I also think that `npm` has decided to drop the long name as well and be just `npm`. 
[npm Wikipedia page](https://en.wikipedia.org/wiki/Npm_(software)) says: 
> npm ([originally short](https://en.wikipedia.org/wiki/Pseudo-acronym) for Node Package Manager)[[4]](https://en.wikipedia.org/wiki/Npm_(software)#cite_note-4)

**Comment by frostming** [comment]
Superseded by #1174

**Pull request closed without merging**
