### PR TITLE
cut local versions with < or > markers

### PR DESCRIPTION
**Pull request by franzhaas**
## Pull Request Checklist

- [ ] A news fragment is added in `news/` describing what is new.
- [x] Test cases added for changed code.

## Describe what you have changed in this PR.

Since a change to packaging (version 22+) we have an issue with our local wheel versions and ">"/"<".

This is a so far only checked with unit tests. Please have a look.

Best regards,
Franz

### CODE REVIEW

**Comment by frostming** [comment]
Can you show a use case of where this will cause a problem?

**Comment by siobz** [comment]
I have a use case for this. We have young projects shared with other groups in the company. If they now use the newest version of pdm, it is not possible to recreate the environment. That is unpleased, after we convinced them to use pdm as a stable solution. Our files look like this:

```toml
dependencies = [
    "ipython",
    "pdoc",
    "numpy",
    "pandas",
    "ct-data-faker",
    "ams-ct-xray-raw-data-parser-analyser",
    "ams-rw-python-register-helper>=0.1.dev31+g294d274",
]
```

**Comment by frostming** [comment]
`ams-rw-python-register-helper>=0.1.dev31+g294d274` would be a bit too strict. In PEP 440 [local versions are not allowed in comparison](https://peps.python.org/pep-0440/#inclusive-ordered-comparison). It would work if you change the specifier to `>=0.1.dev31`

**Comment by franzhaas** [comment]
Yes this is correct. The problem is that when you work with an old state of one of our projects, you can not do so with a recently installed pdm.

It would help us if pdm would cut this local versions for us. This would allow us to reproduce old project states with current tools.

**Comment by frostming** [comment]
> pdm would cut this local versions for us

We are not doing this, breaking the rule brings a risk that other tools consuming the file may not support it.

After all, if the local version is to be stripped in comparison, why do you want to keep it in the `pyproject.toml`.

**Comment by frostming** [comment]
Sorry, we can't update to fit *your* workflow, you know there are thousands of workflows. Downgrade to packaging < 22 if you want to work with legacy version specifiers.

**Comment by franzhaas** [comment]
I am sorry but I have to disagree.

Today I ran into this issue again and figured out how it happened.

I used a machine where pdm 2.3.2 is installed to add a package which is locally hosted with a local version by.:

`pdm add ams-rw-stdf`

the resulting pyproject.toml had this line in it and worked on that machine.:

`dependencies = ["ams-rw-stdf>=0.1.dev154+ge5720d0",]`

I think this is because the installed packaging==21.3

So from my perspective, this is the recommended workflow. While I can update PDM, we still have a lot or pyproject.toml which have been created when pdm version behaving like that were current.

I think it would be great if pdm could forgive these mistakes from the past.

**Comment by frostming** [comment]
> So from my perspective, this is the recommended workflow. While I can update PDM, we still have a lot or pyproject.toml which have been created when pdm version behaving like that were current.

Yes, it was a bug existing on old PDM versions and were not surfaced until the release of packaging 22. This is subject to two attitudes towards the bugs: to tolerate or to ban. We choose to ban and that is it.

**Pull request closed without merging**
