### PR TITLE
Document installing pip with ensurepip

### PR DESCRIPTION
**Pull request by adriangb**

### CODE REVIEW

**Comment by adriangb** [comment]
cc @pawamoy

**Review by pawamoy — APPROVED** [review]
Awesome, thanks!

**Comment by frostming** [comment]
Hmm, I assume people will look for the CLI help when he wants to tweak the behavior: https://pdm.fming.dev/latest/reference/cli/#create

**Comment by adriangb** [comment]
I guess I'll blame mkdocs' search:

image

**Comment by frostming** [comment]
Well, generated content may not be indexed. @pawamoy

**Comment by pawamoy** [comment]
Ha, maybe indeed. I'll check it out.

**Comment by pawamoy** [comment]
Yeah not sure what's happening with the search.

search

If I type `cli virtualenv with pip` instead, it doesn't find the virtualenv word. It also does not find the "with" in "--with-pip" :confused: Maybe @squidfunk's work on the search feature will improve things here :slightly_smiling_face:

**Pull request merged**
