### PR TITLE
chore(ci): remove the duplicate steps of setting up the Python version in the Testing job

### PR DESCRIPTION
**Pull request by Georgehu716**
## Pull Request Checklist

- [ ] A news fragment is added in `news/` describing what is new.
- [ ] Test cases added for changed code.

### CODE REVIEW

**Comment by frostming** [comment]
What is the rationale behind this PR?

**Comment by Georgehu716** [comment]
> What is the rationale behind this PR?

Since macos-latest still use Python3.9, there's no need to include this check. The matrix already specifies `python-version` for each job.

**Comment by frostming** [comment]
> The matrix already specifies `python-version` for each job.

Yeah, but we need more python versions than that for each job. So the integration test case can cover managing projects from 3.9-latest

**Comment by Georgehu716** [comment]
Sorry, I didn't quite understand what you meant. Are there any differences between these two jobs - one after my modification and the other before it?
- https://github.com/pdm-project/pdm/actions/runs/12269238533/job/34232463268
- https://github.com/pdm-project/pdm/actions/runs/12268993329/job/34231807002?pr=3350

**Comment by frostming** [comment]
> Sorry, I didn't quite understand what you meant. Are there any differences between these two jobs - one after my modification and the other before it?

Before: 

```
===== 985 passed, 1 skipped, 1 xfailed, 350 warnings in 130.51s (0:02:10) ======
```

After:

```
====== 984 passed, 1 skipped, 1 xfailed, 280 warnings in 91.47s (0:01:31) ======
```

**Comment by Georgehu716** [comment]
> > Sorry, I didn't quite understand what you meant. Are there any differences between these two jobs - one after my modification and the other before it?
> 
> Before:
> 
> ```
> ===== 985 passed, 1 skipped, 1 xfailed, 350 warnings in 130.51s (0:02:10) ======
> ```
> 
> After:
> 
> ```
> ====== 984 passed, 1 skipped, 1 xfailed, 280 warnings in 91.47s (0:01:31) ======
> ```

Oh, I see. It's missing the `tests/test_integration.py::test_basic_integration[3.10]` test cases, but these will be covered by the matrix strategy.

**Comment by frostming** [comment]
> Oh, I see. It's missing the `tests/test_integration.py::test_basic_integration[3.10]` test cases, but these will be covered by the matrix strategy.

It's actually a 2-d matrix that are all worth covering. Using Python 3.10 to manage Python 3.10 is covered, by using Python 3.9 to manage Python 3.10 is not.

**Pull request closed without merging**
