### PR TITLE
Add option to skip _add_to_path in installer

### PR DESCRIPTION
**Pull request by 1oglop1**
## Pull Request Check List

- [ ] A news fragment is added in `news/` describing what is new.
- [ ] Test cases added for changed code.

## Describe what you have changed in this PR.
I created a [asdf-vm](https://asdf-vm.com/) plugin for PDM https://github.com/1oglop1/asdf-pdm. 
And created an issue to add it to the community plugins #asdf-community/.github/issues/33. 
Also a minor change to a variable name `bin` which was shadowing builtin function `bin`.

### CODE REVIEW

**Comment by 1oglop1** [comment]
I'm not sure how to use `news/`

**Comment by frostming** [comment]
> I'm not sure how to use `news/`

add a news fragment file named `{issue_id}.{type}.md` under `news/`, describing what is changed. In this case file should be named `1145.misc.md`, where `misc` is short for "Miscellany"

**Review by frostming — APPROVED** [review]
LGTM

**Comment by biaocy** [comment]
> For security reasons, you should verify the checksum of install-pdm.py. The sha256 checksum is: 67dccb18923340e21f3d70f9c6a467d532c6a41b295d6f1ba884b27604074d38

Please update the checksum of `install-pdm.py` file as well, or else people who cares about security, like the one who add it in the first place, would feel a little uncertainty if they find out the latest file checksum is not the same as in `README`

**Pull request merged**
